main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.portofolio, name='portofolio'),
    path('blog/', views.blog, name='blog'),
    # path('Schedule/', views.Join, name='Schedule'),
     # path('<int:pk>', views.sched_delete, name='Delete'),
    path('matkul/',views.MatkulJoin, name='Matkul'),
    path('<int:pk>', views.matkul_delete, name='Delete'),
]

storypertama/urls.py
from django.urls import path

from . import views

app_name = 'storypertama'

urlpatterns = [
    path('', views.story1, name='story1'),

]

storyppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/',include('storypertama.urls')) 

]

main/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    Day= models.CharField(max_length=50)
    Date = models.DateField(blank = False)
    Time= models.TimeField()
    Name= models.TextField(max_length=50)
    Location = models.TextField(max_length=50)
    Category = models.TextField(max_length=50)

class Matkul(models.Model):
    Name= models.TextField(max_length=50)
    Sks=models.IntegerField()
    Day=models.CharField(max_length=50)
    Time= models.TimeField()
    Date= models.DateField(blank=False)

storypertama/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

class SchedForm(forms.Form):
    Day= forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Day',
        'type' : 'text',
        'required' : True,
    }))
    Date = forms.DateField(widget=forms.DateInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'dd/mm/yyyy',
        'type': 'date',
        'required': True,
    }))
    Time = forms.TimeField(widget=forms.TimeInput(attrs={
        'class' : 'form-control',
        'type' : 'time',
        'required': True,
    }))
    Name = forms.CharField(widget=forms.TimeInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'placeholder' : 'Activity Name',
        'required': True,
    }))

class MatkulForm(forms.Form):
    Name= forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Matkul',
        'type' : 'text',
        'required' : True,
    }))
    Sks= forms.IntegerField (widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Jumlah SKS',
        'type' : 'text',
        'required' : True,
    }))
    Day= forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Day',
        'type' : 'text',
        'required' : True,
    }))
    Time = forms.TimeField(widget=forms.TimeInput(attrs={
        'class' : 'form-control',
        'type' : 'time',
        'required': True,
    }))
    Date = forms.DateField(widget=forms.DateInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'dd/mm/yyyy',
        'type': 'date',
        'required': True,
    }))
   

main/views.py
from django.shortcuts import render,redirect
from .models import Schedule as jadwal, Matkul as matkul
from .forms import SchedForm, MatkulForm



def portofolio(request):
    return render(request, 'main/portofolio.html')
def blog(request):
    return render(request, 'main/blog.html')
def Join(request):
    if request.method=="POST":
        form=SchedForm(request.POST)
        if form.is_valid():
            sched= jadwal()
            sched.Day = form.cleaned_data['Day']
            sched.Date = form.cleaned_data['Date']
            sched.Time = form.cleaned_data['Time']
            sched.Name = form.cleaned_data['Name']
            # sched.Location = form.cleaned_data['Location']
            # sched.Category = form.cleaned_data['Category']
            sched.save()
        return redirect('/Schedule')
    else:
        sched = jadwal.objects.all()
        form = SchedForm()
        response = {"sched":sched, 'form':form}
        return render (request, 'main/Schedule.html',response)
def sched_delete(request,pk):
    if request.method == "POST":
        form = SchedForm(request.POST)
        if form.is_valid():
            sched= jadwal()
            sched.Day = form.cleaned_data['Day']
            sched.Date = form.cleaned_data['Date']
            sched.Time = form.cleaned_data['Time']
            sched.Name = form.cleaned_data['Name']
            # sched.Location = form.cleaned_data['Location']
            # sched.Category= form.cleaned_data['Category']
            sched.save()
        return redirect('/Schedule')
    else:
        jadwal.objects.filter(pk=pk).delete()
        data= jadwal.objects.all()
        form = SchedForm()
        response={"sched":data, 'form':form}
        return render(request, 'main/Schedule.html', response)


def MatkulJoin(request):
    if request.method=="POST":
        form=MatkulForm(request.POST)
        if form.is_valid():
            matakul= matkul()
            matakul.Name=form.cleaned_data['Name']
            matakul.Sks = form.cleaned_data['Sks']
            matakul.Day = form.cleaned_data['Day']
            matakul.Time = form.cleaned_data['Time']
            matakul.Date = form.cleaned_data['Date']
            matakul.save()
        return redirect('/matkul')
    else:
        matakul = matkul.objects.all()
        form = MatkulForm()
        response = {"matakul":matakul, 'form':form}
        return render (request, 'main/Matkul.html',response)
def matkul_delete(request,pk):
    if request.method == "POST":
        form = MatkulForm(request.POST)
        if form.is_valid():
            matakul= matkul()
            matakul.Name=form.cleaned_data['Name']
            matakul.Sks = form.cleaned_data['Sks']
            matakul.Day = form.cleaned_data['Day']
            matakul.Time = form.cleaned_data['Time']
            matakul.Date = form.cleaned_data['Date']
            matakul.save()
        return redirect('/matkul')
    else:
        matkul.objects.filter(pk=pk).delete()
        data= matkul.objects.all()
        form = MatkulForm()
        response={"matakul":data, 'form':form}
        return render(request, 'main/Matkul.html', response)

storypertama/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'storypertama/story1.html')

main/templates/main/Matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal Kuliah</title>
{% endblock meta %}

{% block content %}
  <form action="" method="POST">
      {% csrf_token %}
      {{form}}
      <div class="center-items">
            <input type="submit" name="btn btn-primary" id="Add Schedule">
      </div>
  </form>
  <table class="table">
      <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">SKS</th>
              <th scope="col">Day</th>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
          </tr>
      </thead>
      <tbody>
          {% for jadwal in matakul %}
            <tr>
                <th scope="row">{{jadwal.Name}}</th>
                <td>{{jadwal.Sks}}</td>
                <td>{{jadwal.Day}}</td>
                <td>{{jadwal.Date}}</td>
                <td>{{jadwal.Time}}</td>
               <td><a href="{% url 'main:Delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"></button></a></td>
            </tr>
            {% endfor %}
      </tbody>

  </table>
  
{% endblock content %}

main/templates/main/Schedule.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Jadwal Kuliah</title>
{% endblock meta %}

{% block content %}
  <form action="" method="POST">
      {% csrf_token %}
      {{form}}
      <div class="center-items">
            <input type="submit" name="btn btn-primary" id="Add Schedule">
      </div>
  </form>
  <table class="table">
      <thead>
          <tr>
              <th scope="col">Day</th>
              <th scope="col">Date</th>
              <th scope="col">Time</th>
              <th scope="col">Name</th>
              <th scope="col">Category</th>
              <th scope="col">Location</th>
              <th scope="col">Delete</th>
          </tr>
      </thead>
      <tbody>
          {% for jadwal in sched %}
            <tr>
                <th scope="row">{{jadwal.Day}}</th>
                <td>{{jadwal.Date}}</td>
                <td>{{jadwal.Time}}</td>
                <td>{{jadwal.Name}}</td>
                <td>{{jadwal.Category}}</td>
                <td>{{jadwal.Location}}</td>
               <td><a href="{% url 'main:Delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"></button></a></td>
            </tr>
            {% endfor %}
      </tbody>

  </table>
  
{% endblock content %}

main/templates/main/blog.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Blog</title>
{% endblock meta %}


{% block content %}
<h2>Let's Read Some of My Article</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="card" style="width: 18rem;" id="card1">
                <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/id/8/81/Monumen_ui_depok.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
                </div>

        </div>
        <div class="col-md-6">
            <div class="card" style="width: 18rem;" id="card2"> 
                <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/a/a7/Coding_%28Unsplash%29.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
                </div>

        </div>
            
                
    </div>
    
        <div class="card mb-3">
        <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/c/cd/Stanford_Oval_May_2011_panorama.jpg" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title">Next Dream</h4>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
        </div>
{% endblock content %}

main/templates/main/form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Matkul</title>
{% endblock meta %}

{% block content %}
<form >
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group">
      <label for="exampleInputFile">File input</label>
      <input type="file" id="exampleInputFile">
      <p class="help-block">Example block-level help text here.</p>
    </div>
    <div class="checkbox">
      <label>
        <input type="checkbox"> Check me out
      </label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
{% endblock content %}

main/templates/main/home.html
<!-- {% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %} -->

main/templates/main/portofolio.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Portofolio</title>
{% endblock meta %}



{% block content %}
<h1>Hi I'm Hazim</h1>
<h4>Short Description</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quibusdam tenetur voluptatum eveniet nisi iste vero sit quasi quae, perferendis porro recusandae molestiae ad maiores ipsa expedita ut iure. Atque!</p>

  <div class="row">
      <div class="col-lg-5 col-sm-10">
        <a href="#">
            <img src="https://www.anime-planet.com/images/characters/hisoka-morow-2619.jpg?t=1589286839" class="" alt="" id="image">
          </a>
      </div>
      <div class="col-lg-6 col-sm-6">
        <table class="table" id="table-1">
            <tbody>
                <tr class="row-1">
                    <td>Name </td>
                    <td>: Muhammad Hazim Al Farouq</td>
                </tr>
                <tr class="row-2">
                    <td>Place & Birth</td>
                    <td>: Jakarta, 10 October 2000</td>
                </tr>
                <tr class="row-3">
                    <td>Education</td>
                    <td>: Bachelor of Computer Science in University of Indonesia</td>
                </tr>
                <tr class="row-4">
                    <td>Achievement</td>
                    <td>: Tidak ada (semoga tahun ini ada)</td>
                </tr>
                <tr class="row-5">
                    <td>Working Experience</td>
                    <td>: Software Engineer at Google (Aamiin)</td>
                </tr>
                <tr class="row-6">
                    <td>Project</td>
                    <td>: Ngerjain tugas & lab</td>
                </tr>
    
            </tbody>
            
        </table>

      </div>
  </div>


    
</table>
{% endblock content %}

storypertama/templates/storypertama/story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 1</title>
{% endblock meta %}

{% block content %}
      <h1>Welcome To My Personal Website</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor dolore fuga eligendi reiciendis eius amet itaque illo autem facere, reprehenderit nostrum aut quo similique ullam tempore expedita deleniti. Ea, tempore.</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident totam autem doloribus saepe eaque, repellat dolorum eius quasi laudantium voluptate itaque aspernatur in veritatis eos sequi temporibus quo, architecto perferendis?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt in praesentium neque voluptates, officiis delectus, porro at amet voluptatum deleniti laudantium fugit obcaecati non rerum? Commodi modi assumenda minus minima?</p>

    <h3>About Me</h3>
        <img src="https://www.anime-planet.com/images/characters/hisoka-morow-2619.jpg?t=1589286839" alt="Foto" width='150' height='200'>
        <table >
           <tr>
               <td>Name:</td>
               <td>Muhammad Hazim Al Farouq</td>
           </tr>
           <tr>
               <td>Birth:</td>
               <td>12 Oktober 2000</td>
           </tr>
           <tr>
               <td>Major:</td>
               <td>Computer Science</td>
           </tr>
           <tr>
               <td>University:</td>
               <td>University Of Indonesia</td>
           </tr>
           <tr>
               <td>NPM:</td>
               <td>1906400103</td>
           </tr>
           <tr>
               <td>Hobby:</td>
               <td>I don't have a specific hobby</td>
           </tr>
           <tr>
               <td>Social media:</td>
               <td>@cobrayyxx</td>
           </tr>
          
         </table>
    <h4>Riwayat Pendidikan</h4>
         <table border=2>
             <tr>
                 <td>SDN Bukit Pamulang Indah</td>
                 <td>2006-2012</td>
            </tr>
            <tr>
                <td>SMPN 17 Tangerang Selatan</td>
                <td>2012-2015</td>
           </tr>
           <tr>
            <td>SMAN 6 Tangerang Selatan</td>
            <td>2015-2018</td>
            </tr>
            <tr>
                <td>Universitas Indonesia</td>
                <td>2019-sekarang</td>
           </tr>
             
         </table>
        
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  {% endblock meta %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>

<body>

  <nav class="navbar navbar-default" id="navbar">
    <div class="navbar-header">
        <a href="#" class="navbar-brand">HSite</a>
    </div>
    <ul class="nav navbar-nav" id="content">
        <li><a href="{% url 'main:blog' %}" id="content">Blog</a></li>
        <li><a href="{% url 'main:portofolio' %}"id="content">Portofolio</a></li>
        <li><a href="{% url 'storypertama:story1' %}"id="content">Story 1</a></li>
        <li><a href="{% url 'main:Matkul' %}"id="content">Schedule</a></li>
      </ul>
  </nav>
  <div class="jumbotron">
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </div>

</body>


</html>